### ISSUE TITLE
Module no longer operational

### ISSUE THREAD

**Issue by LukasPrism** [xaukael/directory-json-drop#1]
As of FVTT 11.307 and dnd5e 2.3.0 it seems that this module is no longer working. No errors in console so unsure if it's v11 or 5e that's causing issues. Crymic brought it to my attention and he's been trying in a range of browsers. He thinks it may be related to 5e expecting explicit item types now?

Many thanks

**Comment by xaukael** [comment]
Does it still work for entities other than actors and items?

**Comment by LukasPrism** [comment]
No it doesn't seem to, so maybe Crymic's hunch wasn't accurate. Hopefully that means it could be a quick fix? I was actually just talking up the module in Tposney's troubleshooter channel on his server the other day because the folk in there who are diagnosing issues are constantly exporting and importing jsons to run tests. I didn't think to test the module first though lol (have only recently moved to v11)

**Comment by xaukael** [comment]
seems renderSidebarDirectory does not happen in v11. Weird. should be an easy fix then.

**Comment by xaukael** [comment]
fixed and updated module compatibility to include 11 now that it is.
